### ISSUE TITLE
mish2jsonl tool fails after build instructions on fresh Ubuntu 20.04 installation, but works on docker image 

### ISSUE THREAD

**Issue by sabastiaan** [trailofbits/mishegos#149]
Problem: Whenever running the mish2jsonl it breaks while it is being run on my main OS shell (Ubuntu 20.04), however running it from a clean docker image it works fine.

The main host had no development tools installed, and ran a copy pasted version of the docker build as an install script without docker setup code. 
All versions between python, python3, pip3 and ruby are identical. All python3 modules from the docker image are also present on the main host. 

The same input file was used across docker and the host.
The input file was tested with both being in /tmp/ and in the root directory of the repository.

Anybody else that ran into this?

```
./src/mish2jsonl/mish2jsonl < /tmp/mishegos

Traceback (most recent call last):
  File "./src/mish2jsonl/mish2jsonl", line 49, in <module>
    main()
  File "./src/mish2jsonl/mish2jsonl", line 12, in main
    cohorts = Cohorts.from_io(sys.stdin.buffer)
  File "/home/$user/.local/lib/python3.8/site-packages/kaitaistruct.py", line 47, in from_io
    return cls(KaitaiStream(io))
  File "/home/$user/dev/mishegos/src/mish2jsonl/cohorts.py", line 26, in __init__
    self._read()
  File "/home/$user/dev/mishegos/src/mish2jsonl/cohorts.py", line 32, in _read
    self.cohorts.append(self._root.Cohort(self._io, self, self._root))
  File "/home/$user/dev/mishegos/src/mish2jsonl/cohorts.py", line 41, in __init__
    self._read()
  File "/home/$user/dev/mishegos/src/mish2jsonl/cohorts.py", line 49, in _read
    self.outputs[i] = self._root.Output(self._io, self, self._root)
  File "/home/$user/dev/mishegos/src/mish2jsonl/cohorts.py", line 58, in __init__
    self._read()
  File "/home/$user/dev/mishegos/src/mish2jsonl/cohorts.py", line 61, in _read
    self.status = KaitaiStream.resolve_enum(self._root.DecodeStatus, self._io.read_u4le())
AttributeError: type object 'KaitaiStream' has no attribute 'resolve_enum'
```

**Comment by woodruffw** [comment]
Hmm, that's interesting. Does anything change if you use `python3-kaitaistruct` from the system package manager instead of the PyPI version?

**Comment by sabastiaan** [comment]
I made sure that there were no other kaitaistruct were installed on my system, got it from my system package manager like you said and got the same problem.

**Comment by woodruffw** [comment]
Figures. Kaitai is a burden in general, so it might be best to replace it completely with our own parser. I'll create an issue for that.

**Comment by woodruffw** [comment]
Obviated by #162.
